<a href="https://colab.research.google.com/github/ayush9h/PyTorch-DeepLearning/blob/main/DL_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Transpose**

In [ ]:
import numpy as np
import torch

In [ ]:
nv = np.array([[1,2,3,4]])
print(nv.T)

[[1]
 [2]
 [3]
 [4]]


In [ ]:
tv = torch.Tensor([[1,2,3,4]])
print(tv.T)

tensor([[1.],
        [2.],
        [3.],
        [4.]])


**Dot Product**

In [7]:
tv1 = torch.Tensor([1,2,3,4])
tv2 = torch.Tensor([2,3,5,6])

print(torch.dot(tv1,tv2))

tensor(47.)


In [8]:
A = torch.randn(3,4)
B = torch.randn(4,5)
print(A@B)

tensor([[ 0.6287, -1.2064,  1.0509,  0.3896, -0.1985],
        [-4.1493, -0.7067, -0.4339, -2.0681,  2.1152],
        [-0.9909, -0.3971, -0.2749,  1.7071,  0.7959]])


In [14]:
C1 = np.random.randn(4,7)
C2 = torch.tensor(C1, dtype=torch.float)
print(A@C1)

print(A@C2)

tensor([[ 0.7542,  0.8856,  0.4466, -0.2916,  2.4079, -0.7860,  0.9516],
        [-2.6410,  1.0342,  0.4448, -1.3418, -1.2033,  0.3255, -0.6242],
        [ 3.3335, -0.8459,  1.9200, -2.0293,  1.4109, -2.5896,  2.6336]],
       dtype=torch.float64)
tensor([[ 0.7542,  0.8856,  0.4466, -0.2916,  2.4079, -0.7860,  0.9516],
        [-2.6410,  1.0342,  0.4448, -1.3418, -1.2033,  0.3255, -0.6242],
        [ 3.3335, -0.8459,  1.9200, -2.0293,  1.4109, -2.5896,  2.6336]])


/tmp/ipython-input-1093889441.py:3: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  print(A@C1)
