<a href="https://colab.research.google.com/github/ayush9h/PyTorch-DeepLearning/blob/main/DL_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Transpose**

In [ ]:
import numpy as np
import torch

In [ ]:
nv = np.array([[1,2,3,4]])
print(nv.T)

[[1]
 [2]
 [3]
 [4]]


In [ ]:
tv = torch.Tensor([[1,2,3,4]])
print(tv.T)

tensor([[1.],
        [2.],
        [3.],
        [4.]])


**Dot Product and MatMul**

In [7]:
tv1 = torch.Tensor([1,2,3,4])
tv2 = torch.Tensor([2,3,5,6])

print(torch.dot(tv1,tv2))

tensor(47.)


In [8]:
A = torch.randn(3,4)
B = torch.randn(4,5)
print(A@B)

tensor([[ 0.6287, -1.2064,  1.0509,  0.3896, -0.1985],
        [-4.1493, -0.7067, -0.4339, -2.0681,  2.1152],
        [-0.9909, -0.3971, -0.2749,  1.7071,  0.7959]])


In [14]:
C1 = np.random.randn(4,7)
C2 = torch.tensor(C1, dtype=torch.float)
print(A@C1)

print(A@C2)

tensor([[ 0.7542,  0.8856,  0.4466, -0.2916,  2.4079, -0.7860,  0.9516],
        [-2.6410,  1.0342,  0.4448, -1.3418, -1.2033,  0.3255, -0.6242],
        [ 3.3335, -0.8459,  1.9200, -2.0293,  1.4109, -2.5896,  2.6336]],
       dtype=torch.float64)
tensor([[ 0.7542,  0.8856,  0.4466, -0.2916,  2.4079, -0.7860,  0.9516],
        [-2.6410,  1.0342,  0.4448, -1.3418, -1.2033,  0.3255, -0.6242],
        [ 3.3335, -0.8459,  1.9200, -2.0293,  1.4109, -2.5896,  2.6336]])


/tmp/ipython-input-1093889441.py:3: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  print(A@C1)


**Softmax**

In [25]:
# From scratch
import math
z = [1,2,3]
ez = [math.exp(i) for i in z]
sum_ez = np.sum(ez)

softmax_res = [i/sum_ez for i in ez]

print(softmax_res)

[np.float64(0.09003057317038046), np.float64(0.24472847105479767), np.float64(0.6652409557748219)]


In [26]:
import torch.nn as nn
softfun = nn.Softmax(dim = 0)
sigmaT = softfun(torch.Tensor(z))

print(sigmaT)

tensor([0.0900, 0.2447, 0.6652])


**Entropy**

In [29]:
H = 0
x = [.25,.75]
for p in x:
  H -= p*np.log(p)
print("Entropy", H)

Entropy 0.5623351446188083


In [33]:
import torch.nn.functional as F
p = [0.0,1.0]
q = [.25,.75]
q_tensor = torch.tensor(q)
p_tensor = torch.tensor(p)

F.binary_cross_entropy(q_tensor, p_tensor)

tensor(0.2877)